# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add-dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_dialog(object):
    def setupUi(self, add_dialog):
        add_dialog.setObjectName("add_dialog")
        add_dialog.resize(589, 473)
        self.buttonBox = QtWidgets.QDialogButtonBox(add_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(220, 440, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_9 = QtWidgets.QLabel(add_dialog)
        self.label_9.setGeometry(QtCore.QRect(240, 20, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.widget = QtWidgets.QWidget(add_dialog)
        self.widget.setGeometry(QtCore.QRect(70, 60, 101, 361))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.splitter = QtWidgets.QSplitter(add_dialog)
        self.splitter.setGeometry(QtCore.QRect(180, 60, 341, 361))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.id_input = QtWidgets.QSpinBox(self.splitter)
        self.id_input.setEnabled(True)
        self.id_input.setObjectName("id_input")
        self.name_input = QtWidgets.QLineEdit(self.splitter)
        self.name_input.setObjectName("name_input")
        self.desc_input = QtWidgets.QLineEdit(self.splitter)
        self.desc_input.setObjectName("desc_input")
        self.isbn_input = QtWidgets.QLineEdit(self.splitter)
        self.isbn_input.setObjectName("isbn_input")
        self.pgs_input = QtWidgets.QSpinBox(self.splitter)
        self.pgs_input.setObjectName("pgs_input")
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yes_rdb = QtWidgets.QRadioButton(self.widget1)
        self.yes_rdb.setObjectName("yes_rdb")
        self.horizontalLayout.addWidget(self.yes_rdb)
        self.no_rdb = QtWidgets.QRadioButton(self.widget1)
        self.no_rdb.setObjectName("no_rdb")
        self.horizontalLayout.addWidget(self.no_rdb)
        self.auth_input = QtWidgets.QLineEdit(self.splitter)
        self.auth_input.setObjectName("auth_input")
        self.year_input = QtWidgets.QSpinBox(self.splitter)
        self.year_input.setObjectName("year_input")

        self.retranslateUi(add_dialog)
        self.buttonBox.accepted.connect(add_dialog.accept)
        self.buttonBox.rejected.connect(add_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(add_dialog)

    def retranslateUi(self, add_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_dialog.setWindowTitle(_translate("add_dialog", "Add Book"))
        self.label_9.setText(_translate("add_dialog", "Add Book"))
        self.label.setText(_translate("add_dialog", "ID"))
        self.label_2.setText(_translate("add_dialog", "Name"))
        self.label_3.setText(_translate("add_dialog", "Description"))
        self.label_4.setText(_translate("add_dialog", "ISBN"))
        self.label_5.setText(_translate("add_dialog", "Page Count"))
        self.label_7.setText(_translate("add_dialog", "Issued"))
        self.label_6.setText(_translate("add_dialog", "Author"))
        self.label_8.setText(_translate("add_dialog", "Year"))
        self.yes_rdb.setText(_translate("add_dialog", "Yes"))
        self.no_rdb.setText(_translate("add_dialog", "No"))
