# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.Dash_tab = QtWidgets.QWidget()
        self.Dash_tab.setObjectName("Dash_tab")
        self.splitter_2 = QtWidgets.QSplitter(self.Dash_tab)
        self.splitter_2.setGeometry(QtCore.QRect(20, 10, 80, 69))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_new_bok = QtWidgets.QPushButton(self.splitter_2)
        self.btn_new_bok.setObjectName("btn_new_bok")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.Dash_tab)
        self.widget.setGeometry(QtCore.QRect(20, 100, 731, 421))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.issued_table = QtWidgets.QTableWidget(self.widget)
        self.issued_table.setColumnCount(8)
        self.issued_table.setObjectName("issued_table")
        self.issued_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.issued_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.issued_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.issued_table.setHorizontalHeaderItem(2, item)
        self.horizontalLayout.addWidget(self.issued_table)
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_edit_iss = QtWidgets.QPushButton(self.widget1)
        self.btn_edit_iss.setObjectName("btn_edit_iss")
        self.verticalLayout.addWidget(self.btn_edit_iss)
        self.btn_delete_iss = QtWidgets.QPushButton(self.widget1)
        self.btn_delete_iss.setObjectName("btn_delete_iss")
        self.verticalLayout.addWidget(self.btn_delete_iss)
        self.btn_ref_iss = QtWidgets.QPushButton(self.widget1)
        self.btn_ref_iss.setObjectName("btn_ref_iss")
        self.verticalLayout.addWidget(self.btn_ref_iss)
        spacerItem = QtWidgets.QSpacerItem(20, 108, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.splitter)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.unissued_table = QtWidgets.QTableWidget(self.widget)
        self.unissued_table.setColumnCount(8)
        self.unissued_table.setObjectName("unissued_table")
        self.unissued_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.unissued_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.unissued_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.unissued_table.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_2.addWidget(self.unissued_table)
        self.splitter_3 = QtWidgets.QSplitter(self.widget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.widget2 = QtWidgets.QWidget(self.splitter_3)
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_edit_uni = QtWidgets.QPushButton(self.widget2)
        self.btn_edit_uni.setObjectName("btn_edit_uni")
        self.verticalLayout_3.addWidget(self.btn_edit_uni)
        self.btn_ref_uni = QtWidgets.QPushButton(self.widget2)
        self.btn_ref_uni.setObjectName("btn_ref_uni")
        self.verticalLayout_3.addWidget(self.btn_ref_uni)
        self.btn_delete_uni = QtWidgets.QPushButton(self.widget2)
        self.btn_delete_uni.setObjectName("btn_delete_uni")
        self.verticalLayout_3.addWidget(self.btn_delete_uni)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.splitter_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.Dash_tab, "")
        self.find_tab = QtWidgets.QWidget()
        self.find_tab.setAccessibleName("")
        self.find_tab.setObjectName("find_tab")
        self.widget3 = QtWidgets.QWidget(self.find_tab)
        self.widget3.setGeometry(QtCore.QRect(40, 30, 761, 401))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.id_input = QtWidgets.QLineEdit(self.widget3)
        self.id_input.setObjectName("id_input")
        self.horizontalLayout_4.addWidget(self.id_input)
        self.btn_serch = QtWidgets.QPushButton(self.widget3)
        self.btn_serch.setObjectName("btn_serch")
        self.horizontalLayout_4.addWidget(self.btn_serch)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.search_table = QtWidgets.QTableWidget(self.widget3)
        self.search_table.setColumnCount(8)
        self.search_table.setObjectName("search_table")
        self.search_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.search_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.search_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.search_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout_5.addWidget(self.search_table)
        self.tabWidget.addTab(self.find_tab, "")
        self.all_tab = QtWidgets.QWidget()
        self.all_tab.setObjectName("all_tab")
        self.all_table = QtWidgets.QTableWidget(self.all_tab)
        self.all_table.setGeometry(QtCore.QRect(10, 90, 781, 366))
        self.all_table.setColumnCount(8)
        self.all_table.setObjectName("all_table")
        self.all_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.all_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.all_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.all_table.setHorizontalHeaderItem(2, item)
        self.widget4 = QtWidgets.QWidget(self.all_tab)
        self.widget4.setGeometry(QtCore.QRect(20, 30, 111, 55))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.btn_ref = QtWidgets.QPushButton(self.widget4)
        self.btn_ref.setObjectName("btn_ref")
        self.verticalLayout_6.addWidget(self.btn_ref)
        self.tabWidget.addTab(self.all_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Actions"))
        self.btn_new_bok.setText(_translate("MainWindow", "New Book"))
        self.label_2.setText(_translate("MainWindow", "Books"))
        self.label_3.setText(_translate("MainWindow", "Issued Books"))
        item = self.issued_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.issued_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.issued_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        self.btn_edit_iss.setText(_translate("MainWindow", "Edit"))
        self.btn_delete_iss.setText(_translate("MainWindow", "Delete"))
        self.btn_ref_iss.setText(_translate("MainWindow", "Refresh"))
        self.label_4.setText(_translate("MainWindow", "Unissued Books"))
        item = self.unissued_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.unissued_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.unissued_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        self.btn_edit_uni.setText(_translate("MainWindow", "Edit"))
        self.btn_ref_uni.setText(_translate("MainWindow", "Refresh"))
        self.btn_delete_uni.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Dash_tab), _translate("MainWindow", "DashBoard"))
        self.label_5.setText(_translate("MainWindow", "Search by ID"))
        self.btn_serch.setText(_translate("MainWindow", "Search"))
        item = self.search_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.search_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.search_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.find_tab), _translate("MainWindow", "Find"))
        item = self.all_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.all_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.all_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        self.label_6.setText(_translate("MainWindow", "All Books"))
        self.btn_ref.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.all_tab), _translate("MainWindow", "All Books"))
